FROM node:22-alpine

WORKDIR /app

# Skopiuj package.json i package-lock.json pliki z listą zależności, aby zainstalować tylko potrzebne pakiety
COPY frontend/package.json .
COPY frontend/package-lock.json* .

# Zainstaluj zależności, clean install
RUN npm ci

# Skopiuj kod frontendu
COPY frontend/ .

# Expose portu dla dev serwera
EXPOSE 5173

# Uruchom dev serwer
CMD ["npm", "run", "dev"]
